[package]
name = "opti-notch"
version = "0.1.2"
edition = "2024"

[dependencies]
skia-safe = "0.153.3"
windows-sys = { version = ">=0.59, <=0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_UI_HiDpi",
    "Win32_System_SystemInformation",
    "Win32_UI_Shell",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Power",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_LibraryLoader",
] }

windows = { version = "0.59", features = [
    "Media_Control",
    "Storage_Streams",
    "Foundation",
    "Foundation_Collections",
] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "blocking"] }
tiny_http = "0.12"
open = "5.3"

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
