[package]
name = "opti-notch"
version = "0.1.0"
edition = "2024"

[dependencies]
floem = { version = "0.2.0", features = ["vger"] }
display-info = "0.5.9"
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_UI_Controls",
] }
