[package]
name = "opti-notch"
version = "0.1.0"
edition = "2024"

[dependencies]
skia-safe = "0.153.3"
windows-sys = { version = ">=0.59, <=0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_UI_HiDpi",
    "Win32_System_SystemInformation",
    "Win32_UI_Shell",
] }

windows = { version = "0.59", features = [
    "Media_Control",
    "Storage_Streams",
    "Foundation",
    "Foundation_Collections",
] }
